# Generated by Django 2.2 on 2021-01-18 09:22

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('marketapp', '0008_auto_20210118_0715'),
    ]

    operations = [
        migrations.CreateModel(
            name='SellerRegister',
            fields=[
                ('myuser', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to=settings.AUTH_USER_MODEL)),
                ('first_name', models.CharField(blank=True, max_length=50, null=True)),
                ('middile_name', models.CharField(blank=True, max_length=50, null=True)),
                ('last_name', models.CharField(blank=True, max_length=50, null=True)),
                ('designation', models.CharField(max_length=50)),
                ('business_of_name', models.CharField(max_length=50)),
                ('mobile_no', models.CharField(blank=True, max_length=50, null=True)),
                ('phone', models.CharField(blank=True, max_length=50, null=True)),
                ('mobile', models.CharField(blank=True, max_length=50, null=True)),
                ('date_corporation', models.DateField()),
            ],
        ),
    ]
