# Generated by Django 2.2 on 2021-01-18 10:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('seller', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sellerregister',
            name='business_of_name',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AlterField(
            model_name='sellerregister',
            name='designation',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AlterField(
            model_name='sellerregister',
            name='first_name',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AlterField(
            model_name='sellerregister',
            name='last_name',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AlterField(
            model_name='sellerregister',
            name='middile_name',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AlterField(
            model_name='sellerregister',
            name='mobile',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AlterField(
            model_name='sellerregister',
            name='mobile_no',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AlterField(
            model_name='sellerregister',
            name='phone',
            field=models.CharField(blank=True, max_length=50),
        ),
    ]
