# Generated by Django 2.2 on 2021-01-18 12:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('seller', '0003_sellerotp'),
    ]

    operations = [
        migrations.CreateModel(
            name='Company_Address',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company_name', models.CharField(blank=True, max_length=256)),
                ('address1', models.CharField(blank=True, max_length=256)),
                ('address12', models.CharField(blank=True, max_length=256)),
                ('city', models.CharField(blank=True, max_length=256)),
                ('country', models.CharField(blank=True, max_length=256)),
                ('pincode', models.CharField(blank=True, max_length=256)),
                ('seller_register', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='seller', to='seller.SellerRegister')),
            ],
        ),
    ]
