# Generated by Django 2.2 on 2021-01-16 20:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('marketapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='myuser',
            name='phone',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
