# Generated by Django 2.2 on 2021-01-17 07:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('marketapp', '0003_phonetoken'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='phonetoken',
            options={},
        ),
        migrations.AlterField(
            model_name='phonetoken',
            name='phone_number',
            field=models.CharField(max_length=50),
        ),
    ]
