# Generated by Django 2.2 on 2021-01-18 05:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('marketapp', '0005_auto_20210117_0729'),
    ]

    operations = [
        migrations.AlterField(
            model_name='myuser',
            name='myuser_choice',
            field=models.CharField(choices=[('A', 'Admin'), ('U', 'User'), ('G', 'Guest')], max_length=1),
        ),
    ]
